[Icon Theme]
Name=Zafiro-icons
Comment=Theme for Lxde or Xfce, by Adolfo Silerio (zayronxio)
Inherits=Numix

# Directory list
Directories=apps/scalable,places/16,places/24,places/48,status/22,

[apps/scalable]
Size=48
Context=Applications
Type=Scalable

[places/16]
Size=16
Context=Pleces
Type=Scalable

[places/24]
Size=24
Context=Pleces
Type=Scalable

[places/48]
Size=48
Context=Pleces
Type=Scalable

[status/22]
Size=22
Context=Status
Type=Threshold
